#ifndef __MACH_LT_ELBA_H
#define __MACH_LT_ELBA_H


/*
 * Physical base addresses
 */
#define LT_ELBA_SMC			(0xEC000000)
#define LT_ELBA_SCC			(0xE0003000)
#define LT_ELBA_DMAC			(0xE0020000)
#define LT_ELBA_L2CC			(0xE0202000)
#define LT_ELBA_MPIC			(0xE0200000)
#define LT_ELBA_INTERNAL_PERIPH		(0xE0000000)
#define ELBA_PERIPH_OFFSET(x)		(x << 12)
#define LT_ELBA_INTERNAL_PERIPH_SIZE	ELBA_PERIPH_OFFSET(24)

#define LT_ELBA_AACI			(LT_ELBA_INTERNAL_PERIPH + ELBA_PERIPH_OFFSET(4))
#define LT_ELBA_KMI0			(LT_ELBA_INTERNAL_PERIPH + ELBA_PERIPH_OFFSET(6))
#define LT_ELBA_KMI1			(LT_ELBA_INTERNAL_PERIPH + ELBA_PERIPH_OFFSET(7))

#define LT_ELBA_UART0			(LT_ELBA_INTERNAL_PERIPH + ELBA_PERIPH_OFFSET(9))
#define LT_ELBA_UART1			(LT_ELBA_INTERNAL_PERIPH + ELBA_PERIPH_OFFSET(10))

#define LT_ELBA_WDT			(LT_ELBA_INTERNAL_PERIPH + ELBA_PERIPH_OFFSET(16))

#define LT_ELBA_SP804_TIMER01		(LT_ELBA_INTERNAL_PERIPH + ELBA_PERIPH_OFFSET(17))
#define LT_ELBA_SP804_TIMER23		(LT_ELBA_INTERNAL_PERIPH + ELBA_PERIPH_OFFSET(18))

#define LT_ELBA_RTC			(LT_ELBA_INTERNAL_PERIPH + ELBA_PERIPH_OFFSET(23))

#define LT_ELBA_A9_MPCORE_GIC_CPU	(LT_ELBA_MPIC + 0x0100)
#define LT_ELBA_A9_MPCORE_GIC_DIST	(LT_ELBA_MPIC + 0x1000)

#define LT_ELBA_A9_MPCORE_SCU		(LT_ELBA_MPIC + 0x0000)
#define LT_ELBA_A9_MPCORE_TWD		(LT_ELBA_MPIC + 0x0600)

#define LT_ELBA_TIMER0			(LT_ELBA_SP804_TIMER01 + 0x000)
#define LT_ELBA_TIMER1			(LT_ELBA_SP804_TIMER01 + 0x020)
#define LT_ELBA_TIMER2			(LT_ELBA_SP804_TIMER23 + 0x000)
#define LT_ELBA_TIMER3			(LT_ELBA_SP804_TIMER23 + 0x020)


#define IRQ_LT_ELBA_WDT			{ (32 + 0) }
#define IRQ_LT_ELBA_TIMER0		(32 + 4)
#define IRQ_LT_ELBA_TIMER1		(32 + 4)
#define IRQ_LT_ELBA_TIMER2		(32 + 5)
#define IRQ_LT_ELBA_TIMER3		(32 + 5)
#define IRQ_LT_ELBA_HDLCD		(32 + 9)
#define IRQ_LT_ELBA_RTC			{ (32 + 10) }
#define IRQ_LT_ELBA_UART0		{ (32 + 12) }
#define IRQ_LT_ELBA_UART1		{ (32 + 13) }
#define IRQ_LT_ELBA_AACI		{ (32 + 19) }
#define IRQ_LT_ELBA_KMI0		{ (32 + 20) }
#define IRQ_LT_ELBA_KMI1		{ (32 + 21) }
#define IRQ_LT_ELBA_DMAC		{ (32 + 24), (32 + 25) }
#define IRQ_LT_ELBA_I2S			(32 + 30)

#ifndef __ASSEMBLY__
extern struct vexpress_tile_desc lt_elba_desc;
extern struct vexpress_tile_desc ct_elba_desc;
#endif
#endif
