obj-$(CONFIG_CPM_BUDDY)	+= buddy.o
obj-$(CONFIG_CPM_GOVTEST)	+= cpm_govtest.o
obj-$(CONFIG_CPM_BANDWIDTH) += ex_bandwidth.o
obj-$(CONFIG_CPM_ALSA) += ex_alsaplay.o
obj-$(CONFIG_CPM_MP3_GSM) += ex_mp3gsm.o
