
obj-$(CONFIG_CPM) += cpm_core.o

obj-$(CONFIG_CPM_GOV_EXHAUSTIVE) += cpm_governor_exhaustive.o

obj-$(CONFIG_CPM_POLICY_SAME) += cpm_policy_dummy.o
obj-$(CONFIG_CPM_POLICY_PERF) += cpm_policy_performance.o

obj-y += test/

