mediatek-drm-objs := mediatek_drm_drv.o \
                  mediatek_drm_crtc.o \
                  mediatek_drm_crtc_main.o \
                  mediatek_drm_ddp.o \
                  mediatek_drm_ddp_comp.o \
                  mediatek_drm_dsi.o \
                  mediatek_drm_fb.o \
                  mediatek_drm_gem.o

obj-$(CONFIG_DRM_MEDIATEK) += mediatek-drm.o

ccflags-y += \
 -Idrivers/gpu/drm
